import type { TrackKey, UserProgress } from "./types";
import { TOTAL_TRACKS } from "./curriculum";

/** Rarity for visual treatment — matches page mapping. */
export type Rarity = "common" | "rare" | "epic" | "legendary";

/**
 * Data-driven achievement definition.
 * Pure: all fields are serializable; no React components here.
 * `unlocked` and `progress` are computed from progress input.
 */
export interface AchievementDef {
  id: string;
  title: string;
  description: string;
  xp: number;
  rarity: Rarity;
  /** Lucide icon key — page maps string -> component. */
  icon: string;
  unlocked: boolean;
  /** 0..1 — min(current/target, 1) */
  progress: number;
  current: number;
  target: number;
}

export interface AchievementProgress extends UserProgress {
  /** Optional certificate tracks the learner has earned (e.g. ["c","python"]) */
  certificates?: string[];
}

type Blueprint = {
  id: string;
  title: string;
  description: string;
  xp: number;
  rarity: Rarity;
  icon: string;
  target: number;
  current: (p: AchievementProgress, total: number) => number;
  unlocked: (p: AchievementProgress, total: number) => boolean;
};

function clamp01(n: number): number {
  if (!Number.isFinite(n)) return 0;
  return Math.max(0, Math.min(1, n));
}

function toBlueprints(input: Blueprint[]): Blueprint[] {
  return input;
}

// Shared helpers — pure, testable
function hasDay(p: AchievementProgress, day: number): boolean {
  return p.completedDays.includes(day);
}
function reachedDay(p: AchievementProgress, day: number): boolean {
  return p.completedDays.some((d) => d >= day);
}
function countDays(p: AchievementProgress): number {
  return p.completedDays.length;
}
function notesCount(p: AchievementProgress): number {
  return Object.keys(p.notes ?? {}).filter((k) => {
    const v = (p.notes as Record<string, string>)[k];
    return typeof v === "string" && v.trim().length > 0;
  }).length;
}
function assignmentsCount(p: AchievementProgress): number {
  return (p.completedAssignments ?? []).length;
}

// ─── Per-track blueprint lists ────────────────────────────────────────────
// Keep existing static achievements as authoritative blueprints — the engine
// derives `unlocked`/`progress` from live progress so the page reacts.

const C_BLUEPRINTS: Blueprint[] = toBlueprints([
  {
    id: "first-boot",
    title: "First Boot",
    description: "Complete Day 1",
    xp: 50,
    rarity: "common",
    icon: "zap",
    target: 1,
    current: (p) => (hasDay(p, 1) ? 1 : 0),
    unlocked: (p) => hasDay(p, 1),
  },
  {
    id: "week-one",
    title: "Week One Survivor",
    description: "Complete 7 days",
    xp: 100,
    rarity: "common",
    icon: "flame",
    target: 7,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 7,
  },
  {
    id: "ten-lessons",
    title: "Ten Lessons Strong",
    description: "Complete 10 days",
    xp: 150,
    rarity: "common",
    icon: "layers",
    target: 10,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 10,
  },
  {
    id: "pointer-fearless",
    title: "Pointer Fearless",
    description: "Reach Day 10 (Pointer Arithmetic)",
    xp: 150,
    rarity: "rare",
    icon: "pointer",
    target: 1,
    current: (p) => (hasDay(p, 10) ? 1 : 0),
    unlocked: (p) => hasDay(p, 10),
  },
  {
    id: "stack-apprentice",
    title: "Stack Apprentice",
    description: "Reach the Apprentice tier (Day 21)",
    xp: 200,
    rarity: "rare",
    icon: "layers",
    target: 1,
    current: (p) => (reachedDay(p, 21) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 21),
  },
  {
    id: "malloc-master",
    title: "Heap Walker",
    description: "Complete Day 13 (Dynamic Memory)",
    xp: 150,
    rarity: "rare",
    icon: "package",
    target: 1,
    current: (p) => (hasDay(p, 13) ? 1 : 0),
    unlocked: (p) => hasDay(p, 13),
  },
  {
    id: "halfway",
    title: "Halfway There",
    description: "Complete 50 days",
    xp: 500,
    rarity: "epic",
    icon: "mountain",
    target: 50,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 50,
  },
  {
    id: "asm-genesis",
    title: "Assembly Genesis",
    description: "Start the Assembly track (Day 51)",
    xp: 200,
    rarity: "rare",
    icon: "cog",
    target: 1,
    current: (p) => (hasDay(p, 51) ? 1 : 0),
    unlocked: (p) => hasDay(p, 51),
  },
  {
    id: "register-expert",
    title: "Register Expert",
    description: "Reach the Expert tier (Day 61)",
    xp: 300,
    rarity: "epic",
    icon: "cpu",
    target: 1,
    current: (p) => (reachedDay(p, 61) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 61),
  },
  {
    id: "streak-7",
    title: "Consistent Operator",
    description: "Maintain a 7-day streak",
    xp: 200,
    rarity: "rare",
    icon: "signal",
    target: 7,
    current: (p) => p.streak,
    unlocked: (p) => p.streak >= 7,
  },
  {
    id: "streak-30",
    title: "Daily Driver",
    description: "Maintain a 30-day streak",
    xp: 500,
    rarity: "legendary",
    icon: "rocket",
    target: 30,
    current: (p) => p.streak,
    unlocked: (p) => p.streak >= 30,
  },
  {
    id: "xp-1000",
    title: "XP Collector",
    description: "Earn 1,000 total XP",
    xp: 100,
    rarity: "common",
    icon: "gem",
    target: 1000,
    current: (p) => p.totalXp,
    unlocked: (p) => p.totalXp >= 1000,
  },
  {
    id: "xp-5000",
    title: "XP Hoarder",
    description: "Earn 5,000 total XP",
    xp: 300,
    rarity: "epic",
    icon: "crown",
    target: 5000,
    current: (p) => p.totalXp,
    unlocked: (p) => p.totalXp >= 5000,
  },
  {
    id: "silicon-master",
    title: "Silicon Master",
    description: "Complete all 100 days",
    xp: 1000,
    rarity: "legendary",
    icon: "star",
    target: 100,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 100,
  },
  {
    id: "assignment-10",
    title: "Assignment Grinder",
    description: "Complete 10 assignments",
    xp: 200,
    rarity: "rare",
    icon: "clipboard",
    target: 10,
    current: (p) => assignmentsCount(p),
    unlocked: (p) => assignmentsCount(p) >= 10,
  },
  {
    id: "notes-5",
    title: "Note Taker",
    description: "Write notes for 5 days",
    xp: 50,
    rarity: "common",
    icon: "clipboard",
    target: 5,
    current: (p) => notesCount(p),
    unlocked: (p) => notesCount(p) >= 5,
  },
  {
    id: "notes-10",
    title: "Archivist",
    description: "Write notes for 10 days",
    xp: 150,
    rarity: "rare",
    icon: "clipboard",
    target: 10,
    current: (p) => notesCount(p),
    unlocked: (p) => notesCount(p) >= 10,
  },
  {
    id: "perfect-notes",
    title: "Perfect Notes",
    description: "Notes for every completed day",
    xp: 250,
    rarity: "epic",
    icon: "star",
    target: 1,
    current: (p) => {
      const c = countDays(p);
      if (c === 0) return 0;
      return notesCount(p) >= c ? 1 : 0;
    },
    unlocked: (p) => {
      const c = countDays(p);
      return c > 0 && notesCount(p) >= c;
    },
  },
  {
    id: "certificate",
    title: "Certified",
    description: "Earn the C certificate",
    xp: 500,
    rarity: "legendary",
    icon: "trophy",
    target: 1,
    current: (p, total) => {
      if (p.certificates?.includes("c")) return 1;
      return countDays(p) >= total ? 1 : 0;
    },
    unlocked: (p, total) => Boolean(p.certificates?.includes("c") || countDays(p) >= total),
  },
]);

const PY_BLUEPRINTS: Blueprint[] = toBlueprints([
  {
    id: "hello-python",
    title: "Hello, Python",
    description: "Complete Day 1",
    xp: 50,
    rarity: "common",
    icon: "braces",
    target: 1,
    current: (p) => (hasDay(p, 1) ? 1 : 0),
    unlocked: (p) => hasDay(p, 1),
  },
  {
    id: "py-week-one",
    title: "Script Apprentice",
    description: "Complete 7 days",
    xp: 100,
    rarity: "common",
    icon: "flame",
    target: 7,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 7,
  },
  {
    id: "py-ten",
    title: "Python Ten",
    description: "Complete 10 days",
    xp: 150,
    rarity: "common",
    icon: "layers",
    target: 10,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 10,
  },
  {
    id: "list-lord",
    title: "List Lord",
    description: "Complete Day 10 (Lists)",
    xp: 150,
    rarity: "rare",
    icon: "layers",
    target: 1,
    current: (p) => (hasDay(p, 10) ? 1 : 0),
    unlocked: (p) => hasDay(p, 10),
  },
  {
    id: "dict-whisperer",
    title: "Dict Whisperer",
    description: "Complete Day 12 (Dictionaries)",
    xp: 150,
    rarity: "rare",
    icon: "pointer",
    target: 1,
    current: (p) => (hasDay(p, 12) ? 1 : 0),
    unlocked: (p) => hasDay(p, 12),
  },
  {
    id: "comprehension",
    title: "One-Liner",
    description: "Complete Day 14 (Comprehensions)",
    xp: 200,
    rarity: "rare",
    icon: "zap",
    target: 1,
    current: (p) => (hasDay(p, 14) ? 1 : 0),
    unlocked: (p) => hasDay(p, 14),
  },
  {
    id: "function-master",
    title: "Function Builder",
    description: "Reach Day 15 (Functions)",
    xp: 150,
    rarity: "rare",
    icon: "package",
    target: 1,
    current: (p) => (reachedDay(p, 15) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 15),
  },
  {
    id: "py-halfway",
    title: "Halfway Through",
    description: "Complete 20 days",
    xp: 300,
    rarity: "epic",
    icon: "mountain",
    target: 20,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 20,
  },
  {
    id: "exception-handler",
    title: "Calm Under Errors",
    description: "Complete Day 21 (Exceptions)",
    xp: 200,
    rarity: "rare",
    icon: "cog",
    target: 1,
    current: (p) => (hasDay(p, 21) ? 1 : 0),
    unlocked: (p) => hasDay(p, 21),
  },
  {
    id: "recursion-hero",
    title: "Recursion Hero",
    description: "Complete Day 30 (Recursion)",
    xp: 300,
    rarity: "epic",
    icon: "cpu",
    target: 1,
    current: (p) => (hasDay(p, 30) ? 1 : 0),
    unlocked: (p) => hasDay(p, 30),
  },
  {
    id: "oop-artisan",
    title: "OOP Artisan",
    description: "Reach Day 34 (Classes)",
    xp: 300,
    rarity: "epic",
    icon: "flask",
    target: 1,
    current: (p) => (reachedDay(p, 34) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 34),
  },
  {
    id: "py-streak-7",
    title: "Consistent Coder",
    description: "Maintain a 7-day streak",
    xp: 200,
    rarity: "rare",
    icon: "signal",
    target: 7,
    current: (p) => p.streak,
    unlocked: (p) => p.streak >= 7,
  },
  {
    id: "py-streak-30",
    title: "Daily Driver",
    description: "Maintain a 30-day streak",
    xp: 500,
    rarity: "legendary",
    icon: "rocket",
    target: 30,
    current: (p) => p.streak,
    unlocked: (p) => p.streak >= 30,
  },
  {
    id: "py-xp-1000",
    title: "XP Collector",
    description: "Earn 1,000 total XP",
    xp: 100,
    rarity: "common",
    icon: "gem",
    target: 1000,
    current: (p) => p.totalXp,
    unlocked: (p) => p.totalXp >= 1000,
  },
  {
    id: "py-xp-5000",
    title: "XP Hoarder",
    description: "Earn 5,000 total XP",
    xp: 300,
    rarity: "epic",
    icon: "crown",
    target: 5000,
    current: (p) => p.totalXp,
    unlocked: (p) => p.totalXp >= 5000,
  },
  {
    id: "py-capstone",
    title: "Python Graduate",
    description: "Complete all 100 days",
    xp: 1000,
    rarity: "legendary",
    icon: "star",
    target: 100,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 100,
  },
  {
    id: "py-assignment-10",
    title: "Assignment Grinder",
    description: "Complete 10 assignments",
    xp: 200,
    rarity: "rare",
    icon: "clipboard",
    target: 10,
    current: (p) => assignmentsCount(p),
    unlocked: (p) => assignmentsCount(p) >= 10,
  },
  {
    id: "py-notes-5",
    title: "Note Taker",
    description: "Write notes for 5 days",
    xp: 50,
    rarity: "common",
    icon: "clipboard",
    target: 5,
    current: (p) => notesCount(p),
    unlocked: (p) => notesCount(p) >= 5,
  },
  {
    id: "py-perfect-notes",
    title: "Perfect Notes",
    description: "Notes for every completed day",
    xp: 250,
    rarity: "epic",
    icon: "star",
    target: 1,
    current: (p) => (countDays(p) > 0 && notesCount(p) >= countDays(p) ? 1 : 0),
    unlocked: (p) => countDays(p) > 0 && notesCount(p) >= countDays(p),
  },
  {
    id: "py-certificate",
    title: "Certified",
    description: "Earn the Python certificate",
    xp: 500,
    rarity: "legendary",
    icon: "trophy",
    target: 1,
    current: (p, total) => (p.certificates?.includes("python") || countDays(p) >= total ? 1 : 0),
    unlocked: (p, total) => Boolean(p.certificates?.includes("python") || countDays(p) >= total),
  },
]);

const CPP_BLUEPRINTS: Blueprint[] = toBlueprints([
  {
    id: "cpp-hello",
    title: "Hello, C++",
    description: "Complete Day 1",
    xp: 50,
    rarity: "common",
    icon: "braces",
    target: 1,
    current: (p) => (hasDay(p, 1) ? 1 : 0),
    unlocked: (p) => hasDay(p, 1),
  },
  {
    id: "cpp-week-one",
    title: "Compiler Apprentice",
    description: "Complete 7 days",
    xp: 100,
    rarity: "common",
    icon: "flame",
    target: 7,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 7,
  },
  {
    id: "cpp-ten",
    title: "Ten Lessons Strong",
    description: "Complete 10 days",
    xp: 150,
    rarity: "common",
    icon: "layers",
    target: 10,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 10,
  },
  {
    id: "cpp-types",
    title: "Type Tamer",
    description: "Reach Day 10",
    xp: 150,
    rarity: "rare",
    icon: "layers",
    target: 1,
    current: (p) => (reachedDay(p, 10) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 10),
  },
  {
    id: "cpp-functions",
    title: "Function Smith",
    description: "Reach Day 15",
    xp: 200,
    rarity: "rare",
    icon: "package",
    target: 1,
    current: (p) => (reachedDay(p, 15) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 15),
  },
  {
    id: "cpp-classes",
    title: "Class Architect",
    description: "Reach Day 21",
    xp: 250,
    rarity: "rare",
    icon: "pointer",
    target: 1,
    current: (p) => (reachedDay(p, 21) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 21),
  },
  {
    id: "cpp-halfway",
    title: "Halfway Through",
    description: "Complete 20 days",
    xp: 300,
    rarity: "epic",
    icon: "mountain",
    target: 20,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 20,
  },
  {
    id: "cpp-stl",
    title: "STL Explorer",
    description: "Reach Day 30",
    xp: 300,
    rarity: "epic",
    icon: "cog",
    target: 1,
    current: (p) => (reachedDay(p, 30) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 30),
  },
  {
    id: "cpp-streak-7",
    title: "Consistent Coder",
    description: "Maintain a 7-day streak",
    xp: 200,
    rarity: "rare",
    icon: "signal",
    target: 7,
    current: (p) => p.streak,
    unlocked: (p) => p.streak >= 7,
  },
  {
    id: "cpp-streak-30",
    title: "Daily Driver",
    description: "Maintain a 30-day streak",
    xp: 500,
    rarity: "legendary",
    icon: "rocket",
    target: 30,
    current: (p) => p.streak,
    unlocked: (p) => p.streak >= 30,
  },
  {
    id: "cpp-xp-1000",
    title: "XP Collector",
    description: "Earn 1,000 total XP",
    xp: 100,
    rarity: "common",
    icon: "gem",
    target: 1000,
    current: (p) => p.totalXp,
    unlocked: (p) => p.totalXp >= 1000,
  },
  {
    id: "cpp-xp-5000",
    title: "XP Hoarder",
    description: "Earn 5,000 total XP",
    xp: 300,
    rarity: "epic",
    icon: "crown",
    target: 5000,
    current: (p) => p.totalXp,
    unlocked: (p) => p.totalXp >= 5000,
  },
  {
    id: "cpp-graduate",
    title: "C++ Graduate",
    description: "Complete all 100 days",
    xp: 1000,
    rarity: "legendary",
    icon: "star",
    target: 100,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 100,
  },
  {
    id: "cpp-assignment-10",
    title: "Assignment Grinder",
    description: "Complete 10 assignments",
    xp: 200,
    rarity: "rare",
    icon: "clipboard",
    target: 10,
    current: (p) => assignmentsCount(p),
    unlocked: (p) => assignmentsCount(p) >= 10,
  },
  {
    id: "cpp-notes-5",
    title: "Note Taker",
    description: "Write notes for 5 days",
    xp: 50,
    rarity: "common",
    icon: "clipboard",
    target: 5,
    current: (p) => notesCount(p),
    unlocked: (p) => notesCount(p) >= 5,
  },
  {
    id: "cpp-perfect-notes",
    title: "Perfect Notes",
    description: "Notes for every completed day",
    xp: 250,
    rarity: "epic",
    icon: "star",
    target: 1,
    current: (p) => (countDays(p) > 0 && notesCount(p) >= countDays(p) ? 1 : 0),
    unlocked: (p) => countDays(p) > 0 && notesCount(p) >= countDays(p),
  },
  {
    id: "cpp-certificate",
    title: "Certified",
    description: "Earn the C++ certificate",
    xp: 500,
    rarity: "legendary",
    icon: "trophy",
    target: 1,
    current: (p, total) => (p.certificates?.includes("cpp") || countDays(p) >= total ? 1 : 0),
    unlocked: (p, total) => Boolean(p.certificates?.includes("cpp") || countDays(p) >= total),
  },
]);

const JS_BLUEPRINTS: Blueprint[] = toBlueprints([
  {
    id: "js-hello",
    title: "Hello, JavaScript",
    description: "Complete Day 1",
    xp: 50,
    rarity: "common",
    icon: "zap",
    target: 1,
    current: (p) => (hasDay(p, 1) ? 1 : 0),
    unlocked: (p) => hasDay(p, 1),
  },
  {
    id: "js-week-one",
    title: "Console Explorer",
    description: "Complete 7 days",
    xp: 100,
    rarity: "common",
    icon: "flame",
    target: 7,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 7,
  },
  {
    id: "js-ten",
    title: "Ten Lessons Strong",
    description: "Complete 10 days",
    xp: 150,
    rarity: "common",
    icon: "layers",
    target: 10,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 10,
  },
  {
    id: "js-functions",
    title: "Function Fan",
    description: "Reach Day 12 (Functions)",
    xp: 150,
    rarity: "rare",
    icon: "pointer",
    target: 1,
    current: (p) => (reachedDay(p, 12) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 12),
  },
  {
    id: "js-arrays",
    title: "Array Artist",
    description: "Complete Day 10 (Array Methods)",
    xp: 150,
    rarity: "rare",
    icon: "layers",
    target: 1,
    current: (p) => (hasDay(p, 10) ? 1 : 0),
    unlocked: (p) => hasDay(p, 10),
  },
  {
    id: "js-closures",
    title: "Closure Crafter",
    description: "Complete Day 15 (Scope & Closures)",
    xp: 200,
    rarity: "rare",
    icon: "package",
    target: 1,
    current: (p) => (hasDay(p, 15) ? 1 : 0),
    unlocked: (p) => hasDay(p, 15),
  },
  {
    id: "js-halfway",
    title: "Halfway Through",
    description: "Complete 20 days",
    xp: 300,
    rarity: "epic",
    icon: "mountain",
    target: 20,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 20,
  },
  {
    id: "js-promises",
    title: "Promise Keeper",
    description: "Reach Day 28 (Promises)",
    xp: 250,
    rarity: "rare",
    icon: "cog",
    target: 1,
    current: (p) => (reachedDay(p, 28) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 28),
  },
  {
    id: "js-ts",
    title: "Typed Up",
    description: "Reach Day 34 (TypeScript)",
    xp: 300,
    rarity: "epic",
    icon: "cpu",
    target: 1,
    current: (p) => (reachedDay(p, 34) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 34),
  },
  {
    id: "js-streak-7",
    title: "Consistent Coder",
    description: "Maintain a 7-day streak",
    xp: 200,
    rarity: "rare",
    icon: "signal",
    target: 7,
    current: (p) => p.streak,
    unlocked: (p) => p.streak >= 7,
  },
  {
    id: "js-streak-30",
    title: "Daily Driver",
    description: "Maintain a 30-day streak",
    xp: 500,
    rarity: "legendary",
    icon: "rocket",
    target: 30,
    current: (p) => p.streak,
    unlocked: (p) => p.streak >= 30,
  },
  {
    id: "js-xp-1000",
    title: "XP Collector",
    description: "Earn 1,000 total XP",
    xp: 100,
    rarity: "common",
    icon: "gem",
    target: 1000,
    current: (p) => p.totalXp,
    unlocked: (p) => p.totalXp >= 1000,
  },
  {
    id: "js-xp-5000",
    title: "XP Hoarder",
    description: "Earn 5,000 total XP",
    xp: 300,
    rarity: "epic",
    icon: "crown",
    target: 5000,
    current: (p) => p.totalXp,
    unlocked: (p) => p.totalXp >= 5000,
  },
  {
    id: "js-graduate",
    title: "JavaScript Graduate",
    description: "Complete all 100 days",
    xp: 1000,
    rarity: "legendary",
    icon: "star",
    target: 100,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 100,
  },
  {
    id: "js-assignment-10",
    title: "Assignment Grinder",
    description: "Complete 10 assignments",
    xp: 200,
    rarity: "rare",
    icon: "clipboard",
    target: 10,
    current: (p) => assignmentsCount(p),
    unlocked: (p) => assignmentsCount(p) >= 10,
  },
  {
    id: "js-notes-5",
    title: "Note Taker",
    description: "Write notes for 5 days",
    xp: 50,
    rarity: "common",
    icon: "clipboard",
    target: 5,
    current: (p) => notesCount(p),
    unlocked: (p) => notesCount(p) >= 5,
  },
  {
    id: "js-perfect-notes",
    title: "Perfect Notes",
    description: "Notes for every completed day",
    xp: 250,
    rarity: "epic",
    icon: "star",
    target: 1,
    current: (p) => (countDays(p) > 0 && notesCount(p) >= countDays(p) ? 1 : 0),
    unlocked: (p) => countDays(p) > 0 && notesCount(p) >= countDays(p),
  },
  {
    id: "js-certificate",
    title: "Certified",
    description: "Earn the JS/TS certificate",
    xp: 500,
    rarity: "legendary",
    icon: "trophy",
    target: 1,
    current: (p, total) => (p.certificates?.includes("js") || countDays(p) >= total ? 1 : 0),
    unlocked: (p, total) => Boolean(p.certificates?.includes("js") || countDays(p) >= total),
  },
]);

const SQL_BLUEPRINTS: Blueprint[] = toBlueprints([
  {
    id: "sql-hello",
    title: "Hello, Data",
    description: "Complete Day 1",
    xp: 50,
    rarity: "common",
    icon: "database",
    target: 1,
    current: (p) => (hasDay(p, 1) ? 1 : 0),
    unlocked: (p) => hasDay(p, 1),
  },
  {
    id: "sql-week-one",
    title: "Row Navigator",
    description: "Complete 7 days",
    xp: 100,
    rarity: "common",
    icon: "flame",
    target: 7,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 7,
  },
  {
    id: "sql-ten",
    title: "Ten Lessons Strong",
    description: "Complete 10 days",
    xp: 150,
    rarity: "common",
    icon: "layers",
    target: 10,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 10,
  },
  {
    id: "sql-select",
    title: "Select Prophet",
    description: "Reach Day 3 (SELECT)",
    xp: 150,
    rarity: "rare",
    icon: "table",
    target: 1,
    current: (p) => (reachedDay(p, 3) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 3),
  },
  {
    id: "sql-aggregates",
    title: "Aggregate Apprentice",
    description: "Reach Day 6 (GROUP BY)",
    xp: 150,
    rarity: "rare",
    icon: "binary",
    target: 1,
    current: (p) => (reachedDay(p, 6) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 6),
  },
  {
    id: "sql-constraints",
    title: "Constraint Enforcer",
    description: "Reach Day 13 (Constraints)",
    xp: 200,
    rarity: "rare",
    icon: "shield",
    target: 1,
    current: (p) => (reachedDay(p, 13) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 13),
  },
  {
    id: "sql-halfway",
    title: "Halfway Through",
    description: "Complete 20 days",
    xp: 300,
    rarity: "epic",
    icon: "mountain",
    target: 20,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 20,
  },
  {
    id: "sql-joins",
    title: "Join Master",
    description: "Complete Day 16 (INNER JOIN)",
    xp: 250,
    rarity: "rare",
    icon: "workflow",
    target: 1,
    current: (p) => (hasDay(p, 16) ? 1 : 0),
    unlocked: (p) => hasDay(p, 16),
  },
  {
    id: "sql-indexes",
    title: "Index Whisperer",
    description: "Reach Day 27 (Indexes)",
    xp: 250,
    rarity: "epic",
    icon: "cpu",
    target: 1,
    current: (p) => (reachedDay(p, 27) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 27),
  },
  {
    id: "sql-transactions",
    title: "Transaction Safe",
    description: "Reach Day 28 (Transactions)",
    xp: 250,
    rarity: "epic",
    icon: "server",
    target: 1,
    current: (p) => (reachedDay(p, 28) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 28),
  },
  {
    id: "sql-streak-7",
    title: "Consistent Coder",
    description: "Maintain a 7-day streak",
    xp: 200,
    rarity: "rare",
    icon: "signal",
    target: 7,
    current: (p) => p.streak,
    unlocked: (p) => p.streak >= 7,
  },
  {
    id: "sql-streak-30",
    title: "Daily Driver",
    description: "Maintain a 30-day streak",
    xp: 500,
    rarity: "legendary",
    icon: "rocket",
    target: 30,
    current: (p) => p.streak,
    unlocked: (p) => p.streak >= 30,
  },
  {
    id: "sql-xp-5000",
    title: "XP Hoarder",
    description: "Earn 5,000 total XP",
    xp: 300,
    rarity: "epic",
    icon: "crown",
    target: 5000,
    current: (p) => p.totalXp,
    unlocked: (p) => p.totalXp >= 5000,
  },
  {
    id: "sql-xp-1000",
    title: "XP Collector",
    description: "Earn 1,000 total XP",
    xp: 100,
    rarity: "common",
    icon: "gem",
    target: 1000,
    current: (p) => p.totalXp,
    unlocked: (p) => p.totalXp >= 1000,
  },
  {
    id: "sql-graduate",
    title: "Database Graduate",
    description: "Complete all 100 days",
    xp: 1000,
    rarity: "legendary",
    icon: "star",
    target: 100,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 100,
  },
  {
    id: "sql-assignment-10",
    title: "Assignment Grinder",
    description: "Complete 10 assignments",
    xp: 200,
    rarity: "rare",
    icon: "clipboard",
    target: 10,
    current: (p) => assignmentsCount(p),
    unlocked: (p) => assignmentsCount(p) >= 10,
  },
  {
    id: "sql-notes-5",
    title: "Note Taker",
    description: "Write notes for 5 days",
    xp: 50,
    rarity: "common",
    icon: "clipboard",
    target: 5,
    current: (p) => notesCount(p),
    unlocked: (p) => notesCount(p) >= 5,
  },
  {
    id: "sql-perfect-notes",
    title: "Perfect Notes",
    description: "Notes for every completed day",
    xp: 250,
    rarity: "epic",
    icon: "star",
    target: 1,
    current: (p) => (countDays(p) > 0 && notesCount(p) >= countDays(p) ? 1 : 0),
    unlocked: (p) => countDays(p) > 0 && notesCount(p) >= countDays(p),
  },
  {
    id: "sql-certificate",
    title: "Certified",
    description: "Earn the SQL certificate",
    xp: 500,
    rarity: "legendary",
    icon: "trophy",
    target: 1,
    current: (p, total) => (p.certificates?.includes("sql") || countDays(p) >= total ? 1 : 0),
    unlocked: (p, total) => Boolean(p.certificates?.includes("sql") || countDays(p) >= total),
  },
]);

const BASH_BLUEPRINTS: Blueprint[] = toBlueprints([
  {
    id: "bash-hello",
    title: "Hello, Shell",
    description: "Complete Day 1",
    xp: 50,
    rarity: "common",
    icon: "terminal",
    target: 1,
    current: (p) => (hasDay(p, 1) ? 1 : 0),
    unlocked: (p) => hasDay(p, 1),
  },
  {
    id: "bash-week-one",
    title: "Pipeline Pilgrim",
    description: "Complete 7 days",
    xp: 100,
    rarity: "common",
    icon: "flame",
    target: 7,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 7,
  },
  {
    id: "bash-ten",
    title: "Ten Lessons Strong",
    description: "Complete 10 days",
    xp: 150,
    rarity: "common",
    icon: "layers",
    target: 10,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 10,
  },
  {
    id: "bash-redirect",
    title: "Redirection Ace",
    description: "Reach Day 5 (Redirection)",
    xp: 150,
    rarity: "rare",
    icon: "harddrive",
    target: 1,
    current: (p) => (reachedDay(p, 5) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 5),
  },
  {
    id: "bash-pipes",
    title: "Pipe Wizard",
    description: "Reach Day 6 (Pipes)",
    xp: 150,
    rarity: "rare",
    icon: "workflow",
    target: 1,
    current: (p) => (reachedDay(p, 6) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 6),
  },
  {
    id: "bash-functions",
    title: "Function Builder",
    description: "Reach Day 14 (Functions)",
    xp: 200,
    rarity: "rare",
    icon: "braces",
    target: 1,
    current: (p) => (reachedDay(p, 14) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 14),
  },
  {
    id: "bash-halfway",
    title: "Halfway Through",
    description: "Complete 20 days",
    xp: 300,
    rarity: "epic",
    icon: "mountain",
    target: 20,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 20,
  },
  {
    id: "bash-grep",
    title: "Text Searcher",
    description: "Reach Day 15 (grep)",
    xp: 200,
    rarity: "rare",
    icon: "fileterminal",
    target: 1,
    current: (p) => (reachedDay(p, 15) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 15),
  },
  {
    id: "bash-git",
    title: "Version Visionary",
    description: "Reach Day 23 (git)",
    xp: 250,
    rarity: "epic",
    icon: "gitbranch",
    target: 1,
    current: (p) => (reachedDay(p, 23) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 23),
  },
  {
    id: "bash-scripts",
    title: "Script Author",
    description: "Reach Day 34 (Scripting)",
    xp: 300,
    rarity: "epic",
    icon: "filecode",
    target: 1,
    current: (p) => (reachedDay(p, 34) ? 1 : 0),
    unlocked: (p) => reachedDay(p, 34),
  },
  {
    id: "bash-streak-7",
    title: "Consistent Coder",
    description: "Maintain a 7-day streak",
    xp: 200,
    rarity: "rare",
    icon: "signal",
    target: 7,
    current: (p) => p.streak,
    unlocked: (p) => p.streak >= 7,
  },
  {
    id: "bash-streak-30",
    title: "Daily Driver",
    description: "Maintain a 30-day streak",
    xp: 500,
    rarity: "legendary",
    icon: "rocket",
    target: 30,
    current: (p) => p.streak,
    unlocked: (p) => p.streak >= 30,
  },
  {
    id: "bash-xp-5000",
    title: "XP Hoarder",
    description: "Earn 5,000 total XP",
    xp: 300,
    rarity: "epic",
    icon: "crown",
    target: 5000,
    current: (p) => p.totalXp,
    unlocked: (p) => p.totalXp >= 5000,
  },
  {
    id: "bash-xp-1000",
    title: "XP Collector",
    description: "Earn 1,000 total XP",
    xp: 100,
    rarity: "common",
    icon: "gem",
    target: 1000,
    current: (p) => p.totalXp,
    unlocked: (p) => p.totalXp >= 1000,
  },
  {
    id: "bash-graduate",
    title: "Toolkit Graduate",
    description: "Complete all 100 days",
    xp: 1000,
    rarity: "legendary",
    icon: "star",
    target: 100,
    current: (p) => countDays(p),
    unlocked: (p) => countDays(p) >= 100,
  },
  {
    id: "bash-assignment-10",
    title: "Assignment Grinder",
    description: "Complete 10 assignments",
    xp: 200,
    rarity: "rare",
    icon: "clipboard",
    target: 10,
    current: (p) => assignmentsCount(p),
    unlocked: (p) => assignmentsCount(p) >= 10,
  },
  {
    id: "bash-notes-5",
    title: "Note Taker",
    description: "Write notes for 5 days",
    xp: 50,
    rarity: "common",
    icon: "clipboard",
    target: 5,
    current: (p) => notesCount(p),
    unlocked: (p) => notesCount(p) >= 5,
  },
  {
    id: "bash-perfect-notes",
    title: "Perfect Notes",
    description: "Notes for every completed day",
    xp: 250,
    rarity: "epic",
    icon: "star",
    target: 1,
    current: (p) => (countDays(p) > 0 && notesCount(p) >= countDays(p) ? 1 : 0),
    unlocked: (p) => countDays(p) > 0 && notesCount(p) >= countDays(p),
  },
  {
    id: "bash-certificate",
    title: "Certified",
    description: "Earn the Bash certificate",
    xp: 500,
    rarity: "legendary",
    icon: "trophy",
    target: 1,
    current: (p, total) => (p.certificates?.includes("bash") || countDays(p) >= total ? 1 : 0),
    unlocked: (p, total) => Boolean(p.certificates?.includes("bash") || countDays(p) >= total),
  },
]);

const BLUEPRINTS: Record<TrackKey, Blueprint[]> = {
  c: C_BLUEPRINTS,
  python: PY_BLUEPRINTS,
  cpp: CPP_BLUEPRINTS,
  js: JS_BLUEPRINTS,
  sql: SQL_BLUEPRINTS,
  bash: BASH_BLUEPRINTS,
};

/**
 * Build achievements for a track from live progress.
 * Pure — no I/O, no React. Returns every achievement with `unlocked` and `progress` (0..1).
 */
export function buildAchievements(
  track: TrackKey,
  progress: AchievementProgress
): AchievementDef[] {
  const total = TOTAL_TRACKS[track] ?? 0;
  const list = BLUEPRINTS[track] ?? [];
  return list.map((b) => {
    const cur = b.current(progress, total);
    const unl = b.unlocked(progress, total);
    const prog = b.target > 0 ? clamp01(cur / b.target) : unl ? 1 : 0;
    return {
      id: b.id,
      title: b.title,
      description: b.description,
      xp: b.xp,
      rarity: b.rarity,
      icon: b.icon,
      unlocked: unl,
      progress: prog,
      current: cur,
      target: b.target,
    };
  });
}

/** Legacy static sets kept as fallback — engine is authoritative. */
export const LEGACY_ACHIEVEMENT_IDS: Record<TrackKey, string[]> = {
  c: C_BLUEPRINTS.map((b) => b.id),
  python: PY_BLUEPRINTS.map((b) => b.id),
  cpp: CPP_BLUEPRINTS.map((b) => b.id),
  js: JS_BLUEPRINTS.map((b) => b.id),
  sql: SQL_BLUEPRINTS.map((b) => b.id),
  bash: BASH_BLUEPRINTS.map((b) => b.id),
};
